
[build]
  publish = ".next"
  command = "npm run build"

[functions]
  included_files = ["gfi-grants/**.json"]

[context.deploy-preview]
  environment = { NEXT_PUBLIC_GRAPHQL_URL = "https://api.thegraph.com/subgraphs/name/pugbyte/goldfinch" }