---
version: "2.1"
services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-storage
    environment:
      - TZ=America/Toronto
    volumes:
      - data:/data/ipfs
    ports:
      - 80:80
      - 4004:4001
      - 5001:5001
      - 8080:8080
      - 443:443 #optional
volumes:
  data:
